// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASrag7lCBDmvhjhYotCE1zGq3bj3t0rkA',
    appId: '1:984009292270:web:7fcc08b4a90f3a999db6ff',
    messagingSenderId: '984009292270',
    projectId: 'vidyasarthi-7fcd4',
    authDomain: 'vidyasarthi-7fcd4.firebaseapp.com',
    storageBucket: 'vidyasarthi-7fcd4.firebasestorage.app',
    measurementId: 'G-C4854CDWZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuKJFXYs9BAxa-iH_0Q3261dOZ38F-oY8',
    appId: '1:984009292270:android:4c22caf52ba827869db6ff',
    messagingSenderId: '984009292270',
    projectId: 'vidyasarthi-7fcd4',
    storageBucket: 'vidyasarthi-7fcd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlDCqR0UnesBNJUdn6HOhLCM-Qr83OBzU',
    appId: '1:984009292270:ios:d908e406fcb3fcac9db6ff',
    messagingSenderId: '984009292270',
    projectId: 'vidyasarthi-7fcd4',
    storageBucket: 'vidyasarthi-7fcd4.firebasestorage.app',
    iosBundleId: 'com.quick.vidyasarthi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlDCqR0UnesBNJUdn6HOhLCM-Qr83OBzU',
    appId: '1:984009292270:ios:d908e406fcb3fcac9db6ff',
    messagingSenderId: '984009292270',
    projectId: 'vidyasarthi-7fcd4',
    storageBucket: 'vidyasarthi-7fcd4.firebasestorage.app',
    iosBundleId: 'com.quick.vidyasarthi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASrag7lCBDmvhjhYotCE1zGq3bj3t0rkA',
    appId: '1:984009292270:web:c98ab4dd2198d1d89db6ff',
    messagingSenderId: '984009292270',
    projectId: 'vidyasarthi-7fcd4',
    authDomain: 'vidyasarthi-7fcd4.firebaseapp.com',
    storageBucket: 'vidyasarthi-7fcd4.firebasestorage.app',
    measurementId: 'G-J7N1B9449L',
  );

}