// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPmNmi3NTTAdYrQEoWEGnyObVte-olqHQ',
    appId: '1:919983361967:web:4b7788ca857a0a325c295a',
    messagingSenderId: '919983361967',
    projectId: 'stsexam-a5988',
    authDomain: 'stsexam-a5988.firebaseapp.com',
    storageBucket: 'stsexam-a5988.firebasestorage.app',
    measurementId: 'G-GRPZ6VTQ2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCSGNGSAx_ojeOu-SXB9DZBjUaMnyrsPQ',
    appId: '1:919983361967:android:afdc364490ad44f95c295a',
    messagingSenderId: '919983361967',
    projectId: 'stsexam-a5988',
    storageBucket: 'stsexam-a5988.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDikN9D__0pPPBjnbwjcEWgE8tRvKU36uI',
    appId: '1:919983361967:ios:2aecc1fd3de9d0b25c295a',
    messagingSenderId: '919983361967',
    projectId: 'stsexam-a5988',
    storageBucket: 'stsexam-a5988.firebasestorage.app',
    iosBundleId: 'com.quick.stsexam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDikN9D__0pPPBjnbwjcEWgE8tRvKU36uI',
    appId: '1:919983361967:ios:2aecc1fd3de9d0b25c295a',
    messagingSenderId: '919983361967',
    projectId: 'stsexam-a5988',
    storageBucket: 'stsexam-a5988.firebasestorage.app',
    iosBundleId: 'com.quick.stsexam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPmNmi3NTTAdYrQEoWEGnyObVte-olqHQ',
    appId: '1:919983361967:web:6646a2c9a11f53305c295a',
    messagingSenderId: '919983361967',
    projectId: 'stsexam-a5988',
    authDomain: 'stsexam-a5988.firebaseapp.com',
    storageBucket: 'stsexam-a5988.firebasestorage.app',
    measurementId: 'G-NW0Y7YFTMW',
  );
}
